config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations =>  "registrations", sessions: 'sessions'}
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end
  devise_scope :user do
    get 'signout',  to: 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "topic_of_interests#index"
  resource :users
  resource :topic_of_interests
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/topic_of_interest.rb
class TopicOfInterest < ApplicationRecord
  has_and_belongs_to_many :users
  validates :topic_name, presence: true, :uniqueness => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_and_belongs_to_many :topic_of_interests

  validates :email, presence: true, :uniqueness => true
  validates :full_name, :presence => true, :length => { :in => 3..20 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def create
    @user = User.new(signup_params)
    if @user.save
      flash[:notice] = "You signed up successfully"
    else
      flash[:notice] = "Form is invalid"
    end
    render "new"
  end

  private

  def signup_params
    params.require(:user).permit(:full_name,
                                        :age,
                                        :email,
                                        :password,
                                        :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:full_name,
                                 :age,
                                 :email,
                                 :password,
                                 :password_confirmation,
                                 :current_password)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  prepend_before_action :require_no_authentication, only: [:new, :create]
  prepend_before_action :allow_params_authentication!, only: :create
  prepend_before_action :verify_signed_out_user, only: :destroy
  prepend_before_action(only: [:create, :destroy]) { request.env["devise.skip_timeout"] = true }

  # GET /resource/sign_in
  def new
    self.resource = resource_class.new(sign_in_params)
    clean_up_passwords(resource)
    yield resource if block_given?
    respond_with(resource, serialize_options(resource))
  end

  # POST /resource/sign_in
  def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)
    yield resource if block_given?
    respond_with resource, location: after_sign_in_path_for(resource)
  end

  # DELETE /resource/sign_out
  def destroy
    signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
    set_flash_message! :notice, :signed_out if signed_out
    yield if block_given?
    respond_to_on_destroy
  end

  protected

  def sign_in_params
    devise_parameter_sanitizer.sanitize(:sign_in)
  end

  def serialize_options(resource)
    methods = resource_class.authentication_keys.dup
    methods = methods.keys if methods.is_a?(Hash)
    methods << :password if resource.respond_to?(:password)
    { methods: methods, only: [:password] }
  end

  def auth_options
    { scope: resource_name, recall: "#{controller_path}#new" }
  end

  def translation_scope
    'devise.sessions'
  end

  private

  # Check if there is no signed in user before doing the sign out.
  #
  # If there is no signed in user, it will set the flash message and redirect
  # to the after_sign_out path.
  def verify_signed_out_user
    if all_signed_out?
      set_flash_message! :notice, :already_signed_out

      respond_to_on_destroy
    end
  end

  def all_signed_out?
    users = Devise.mappings.keys.map { |s| warden.user(scope: s, run_callbacks: false) }

    users.all?(&:blank?)
  end

  def respond_to_on_destroy
    # We actually need to hardcode this as Rails default responder doesn't
    # support returning empty response on GET request
    respond_to do |format|
      format.all { head :no_content }
      format.any(*navigational_formats) { redirect_to after_sign_out_path_for(resource_name) }
    end
  end
end

app/controllers/topic_of_interests_controller.rb
class TopicOfInterestsController < ApplicationController
  before_action :authenticate_user!, only: :new

  def index
    @topic_of_interests = current_user.present? ? current_user.topic_of_interests : TopicOfInterest.all.limit(20)
  end

  def new
    @topic = TopicOfInterest.new
  end

  def create
    if current_user.topic_of_interests.create(topic_params)
      flash[:notice] = "You signed up successfully"
    else
      flash[:notice] = "Form is invalid"
    end
    redirect_to root_path
  end

  private

  def topic_params
    params.require(:topic_of_interest).permit(:topic_name, :short_desc, :user_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: :new

  def new
    @user = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/topic_of_interests_helper.rb
module TopicOfInterestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Xcelerator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/topic_of_interests/index.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Xcelerator</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <% uri =  current_user.present? ? [destroy_user_session_path, 'Logout'] : [new_user_session_path, 'Login'] %>
      <li><a href="<%= uri[0] %>"><span class="glyphicon glyphicon-log-in"></span> <%= uri[1] %></a></li>
    </ul>
  </div>
</nav>

<% if current_user.present? %>
  <a href="<%= new_topic_of_interests_path  %>" type="button" class="btn btn-success pull-right">Add Topic</a>
<% end %>
<div class="container">
  <h2>List of Topics</h2>
  <table class="table table-hover">
    <thead>
    <tr>
      <th>Topic Name</th>
      <th>Description</th>
    </tr>
    </thead>
    <tbody>
    <% @topic_of_interests.each do |topic|  %>
      <tr>
        <td><%= topic.topic_name %></td>
        <td><%= topic.short_desc %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/topic_of_interests/new.html.erb
<div class="container" style="padding-top: 20rem">
  <%= form_for(:topic_of_interest, :url => topic_of_interests_path, html: {class: "form-horizontal"}, method: :post) do |f| %>
    <div class="form-group">
      <%= f.label :topic_name, class: "control-label col-sm-2" %>
      <div class="col-sm-6">
        <%= f.text_field :topic_name, class: "form-control", placeholder: "Enter topic name" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :short_desc, class: "control-label col-sm-2" %>
      <div class="col-sm-6">
        <%= f.text_field :short_desc, class: "form-control", placeholder: "Enter topic desc.." %>
      </div>
    </div>
    <input type="hidden" name="topic_of_interest[user_id]" value="<%= current_user.id %>">
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-default">Submit</button>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="container">
  <h2>SignUp</h2>
  <%= form_for(:user, :url => {:controller => 'users', :action => 'create'}, html: {class: "form-horizontal"}) do |f| %>
    <div class="form-group">
      <%= f.label :full_name, class: "control-label col-sm-2" %>
      <div class="col-sm-6">
        <%= f.text_field :full_name, class: "form-control", placeholder: "Enter full name" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :age, class: "control-label col-sm-2" %>
      <div class="col-sm-6">
        <%= f.date_field :age, class: "form-control", placeholder: "Enter your age" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :email, class: "control-label col-sm-2" %>
      <div class="col-sm-6">
        <%= f.text_field :email, class: "form-control", placeholder: "Enter email" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :password, class: "control-label col-sm-2" %>
      <div class="col-sm-6">
        <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-default">Submit</button>
      </div>
    </div>
  <% end %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_users_path(resource_name), {style: "margin-left: 14rem"} %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), {style: "margin-left: 14rem"} %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>